apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-app02
  template:
    metadata:
      labels:
        app: my-nginx-app02
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 8080
