apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-cip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-app01
  template:
    metadata:
      labels:
        app: my-nginx-app01
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
