apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service02
spec:
  selector:
    app: my-nginx-app02
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer